def chapter(title: str, content: str, kg: str) -> str:
    """Format chapter content for LaTeX"""
    # Escape special LaTeX characters
    special_chars=['\\', '{', '}', '&', '#', '$', '^', '_', '~', '%']
    for char in special_chars:
        content=content.replace(char, f'\\{char}')
        title=title.replace(char, f'\\{char}')

    # Format content with proper spacing
    content=content.replace('\n', '\n\n'+kg)

    return f"""
\\section{{{title}}}
{content}
"""

def header(title: str) -> str:
    """Create LaTeX document header"""
    return f"""\\documentclass[12pt,a4paper]{{article}}
\\usepackage{{ctex}}
\\usepackage{{geometry}}
\\usepackage{{hyperref}}
\\usepackage{{bookmark}}

\\geometry{{
    top=2.54cm,
    bottom=2.54cm,
    left=3.18cm,
    right=3.18cm
}}

\\title{{{title}}}
\\author{{Generated by NovelDownloader}}
\\date{{\\today}}

\\begin{{document}}
\\maketitle
\\tableofcontents
\\newpage
"""
